### ISSUE TITLE
Crash on nil value in response["releasedAt"] (card.rb)

### ISSUE THREAD

**Issue by pfirpfel** [chasepark/MtgDbClient#1]
## Script to reproduce:

``` ruby
require "MtgDbClient"
client = MtgDbClient::Client.new
# C14 version of Flickerwisp has null at releasedAt
card = client.get_card_by_name('Flickerwisp')
```

leads to:

```
TypeError: no implicit conversion of nil into String
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/MtgDbClient-0.0.3/lib/MtgDbClient/card.rb:34:in `parse'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/MtgDbClient-0.0.3/lib/MtgDbClient/card.rb:34:in `initialize'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/MtgDbClient-0.0.3/lib/MtgDbClient/client.rb:75:in `new'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/MtgDbClient-0.0.3/lib/MtgDbClient/client.rb:75:in `block in get_card_by_name'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/httparty-0.13.3/lib/httparty/response.rb:62:in `map'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/httparty-0.13.3/lib/httparty/response.rb:62:in `method_missing'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/MtgDbClient-0.0.3/lib/MtgDbClient/client.rb:75:in `get_card_by_name'
        from (irb):5
        from c:/Ruby200-x64/bin/irb:12:in `<main>'
```
## Suggestion

In the constructor of card.rb change the following line (~line 32):

``` ruby
self.released_at = Date.parse(response["releasedAt"])
```

to something like:

``` ruby
self.released_at = Date.parse(response["releasedAt"]) unless response["releasedAt"].nil?
```

**Comment by chasepark** [comment]
Merged, thank you!
