### ISSUE TITLE
get_card_by_name crashes on HTTP 404

### ISSUE THREAD

**Issue by pfirpfel** [chasepark/MtgDbClient#3]
``` ruby
require "MtgDbClient"
client = MtgDbClient::Client.new
# produces this query: http://api.mtgdb.info/cards/Dead%20/%20Gone
card = client.get_card_by_name('Dead / Gone')
```

leads to:

```
NoMethodError: undefined method `map' for #<HTTParty::Response:0x0000000267f438>
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/httparty-0.13.3/lib/httparty/response.rb:66:in `method_missing'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/MtgDbClient-0.0.3/lib/MtgDbClient/client.rb:75:in `get_card_by_name'
        from (irb):42
        from c:/Ruby200-x64/bin/irb:12:in `<main>'
```

I recommend checking for a HTTP 200 (OK) or 304 (not modified) before continuing processing the card data.

**Comment by chasepark** [comment]
Tests were written around the issue, and the issue was resolved. Thanks!
